### ISSUE TITLE
Link to completed survey goes to 404

### ISSUE THREAD

**Issue by everruler12** [Street-Epistemology/se-survey-beta#1]
There seems to be a problem with github.io routing for links like https://street-epistemology.github.io/BAAAAAAAAAAA

**Comment by FKonGithub** [comment]
> There seems to be a problem with github.io routing for links like https://street-epistemology.github.io/BAAAAAAAAAAA

The official survey is here: https://se-survey.web.app/

This version was more of an experiment. I will be replaced with a list of projects today.
